" Generated by vim-plug
" 2026-09-11T23:03:38 CEST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['FastFold'].commit = 'c1ddfa1a0e00316d1161ce11438ec980348b8cb9'
silent! let g:plugs['ale'].commit = 'e1789bc54483d76ac9ddb40b633d1645c8281914'
silent! let g:plugs['black'].commit = '20622e1259c29bda81831962ace1348ba1921c84'
silent! let g:plugs['coverage-highlight.vim'].commit = '2b7371e852ae362090262c78e2cb1233ecfbd73e'
silent! let g:plugs['delimitMate'].commit = 'becbd2d353a2366171852387288ebb4b33a02487'
silent! let g:plugs['dracula'].commit = 'e7817b4baccfb3529f709ac048c621f35cdbc5b3'
silent! let g:plugs['fzf'].commit = '758b1ac73d7af4db940a5963f844f593dfb0feda'
silent! let g:plugs['fzf.vim'].commit = '8a0068127ac9ee23d71dab2944ce995726bef462'
silent! let g:plugs['indentLine'].commit = 'b96a75985736da969ac38b72a7716a8c57bdde98'
silent! let g:plugs['jedi-vim'].commit = 'a13c7bf64dbb4abcf676b4e41c5fedc2d4e7f6dd'
silent! let g:plugs['markdown-preview.nvim'].commit = 'a923f5fc5ba36a3b17e289dc35dc17f66d0548ee'
silent! let g:plugs['nerdtree'].commit = '690d061b591525890f1471c6675bcb5bdc8cdff9'
silent! let g:plugs['plantuml-syntax'].commit = '9d4900aa16674bf5bb8296a72b975317d573b547'
silent! let g:plugs['requirements.txt.vim'].commit = 'd55452136a162ac31b15876ab98c00bd1b6c312f'
silent! let g:plugs['tagbar'].commit = '07cb8247487208124978daff8e13624667635457'
silent! let g:plugs['ultisnips'].commit = '0ca6a21386021e74a91034365809dcca56ed13f0'
silent! let g:plugs['vim-abolish'].commit = 'dcbfe065297d31823561ba787f51056c147aa682'
silent! let g:plugs['vim-airline'].commit = 'ae24f4aca06731d5d7224df1fc5415975331b214'
silent! let g:plugs['vim-airline-themes'].commit = '77aab8c6cf7179ddb8a05741da7e358a86b2c3ab'
silent! let g:plugs['vim-coiled-snake'].commit = '7a8098aa268e56bfc5f7fa19375faf6c51c996a2'
silent! let g:plugs['vim-commentary'].commit = '64a654ef4a20db1727938338310209b6a63f60c9'
silent! let g:plugs['vim-compiler-pytest'].commit = 'e7a137fcc0038c3859093fbd46a7578e0d564a94'
silent! let g:plugs['vim-fugitive'].commit = '3b753cf8c6a4dcde6edee8827d464ba9b8c4a6f0'
silent! let g:plugs['vim-gitgutter'].commit = '90b75207bd9b55d8ac4af15f72b4e935462014d0'
silent! let g:plugs['vim-misc'].commit = '3e6b8fb6f03f13434543ce1f5d24f6a5d3f34f0b'
silent! let g:plugs['vim-python-pep8-indent'].commit = '60ba5e11a61618c0344e2db190210145083c91f8'
silent! let g:plugs['vim-rhubarb'].commit = '5496d7c94581c4c9ad7430357449bb57fc59f501'
silent! let g:plugs['vim-session'].commit = '9e9a6088f0554f6940c19889d0b2a8f39d13f2bb'
silent! let g:plugs['vim-sleuth'].commit = 'be69bff86754b1aa5adcbb527d7fcd1635a84080'
silent! let g:plugs['vim-snippets'].commit = 'ededcf7581962ee616cadab360d5966f3307f11a'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-unimpaired'].commit = 'db65482581a28e4ccf355be297f1864a4e66985c'
silent! let g:plugs['wmgraphviz.vim'].commit = 'f08ff5becd1e6e81d681ff2926f2cce29f63cb18'

PlugUpdate!

